services:
  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - server
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${SERVER_PORT}:81

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./server/.docker/db/data:/var/lib/mysql
      - ./server/.docker/db/logs:/var/log/mysql
      - ./server/.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./server/.docker/db/sql:/docker-entrypoint-initdb.d
    restart: always

  ####################################################################################################
  # SERVER
  ####################################################################################################
  server:
    container_name: server
    image: server:latest
    build:
      context: ./server/.docker/php
    volumes:
      - ./server:/var/www/server:cached
    depends_on:
      - mysql

volumes:
  node_modules: {}
